'use strict';

import { QueryInterface } from "sequelize";

/** @type {import('sequelize-cli').Migration} */
export default {
  up: (queryInterface: QueryInterface) => {
    return queryInterface.bulkInsert('Order', [
      {
        user_id: 1,
        restaurant_id: 2,
        order_total: 450,
        delivery_status: "pending",
        driver_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 1,
        restaurant_id: 2,
        order_total: 250,
        delivery_status: "pending",
        driver_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 1,
        restaurant_id: 2,
        order_total: 625,
        delivery_status: "pending",
        driver_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 1,
        restaurant_id: 1,
        order_total: 748,
        delivery_status: "pending",
        driver_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 1,
        restaurant_id: 1,
        order_total: 250,
        delivery_status: "pending",
        driver_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 2,
        restaurant_id: 3,
        order_total: 250,
        delivery_status: "pending",
        driver_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 3,
        restaurant_id: 4,
        order_total: 421,
        delivery_status: "pending",
        driver_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 3,
        restaurant_id: 3,
        order_total: 325,
        delivery_status: "pending",
        driver_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 3,
        restaurant_id: 1,
        order_total: 394,
        delivery_status: "pending",
        driver_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 4,
        restaurant_id: 3,
        order_total: 495,
        delivery_status: "pending",
        driver_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 4,
        restaurant_id: 2,
        order_total: 314,
        delivery_status: "pending",
        driver_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 4,
        restaurant_id: 2,
        order_total: 250,
        delivery_status: "pending",
        driver_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 4,
        restaurant_id: 2,
        order_total: 180,
        delivery_status: "pending",
        driver_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 4,
        restaurant_id: 2,
        order_total: 250,
        delivery_status: "pending",
        driver_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },
  down: (queryInterface: QueryInterface) => {
    return queryInterface.bulkDelete('Order', {});
  },
};
